# Generated by Django 4.1.4 on 2023-04-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_employee_company_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
    ]
